url: "legoraft.com"
baseurl: "/"
permalink: /posts/:title
timezone: Europe/Amsterdam

title: "Legoraft's blog"
description: "My personal blog, where I write about things I find interesting and stuff I like."

author: "legoraft"
logo: "/assets/icons/logo.png"
social:
  name: Legoraft
  links:
    - https://mastodon.social/@legoraft
    - https://github.com/legoraft
    - https://codeberg.org/legoraft

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
