title:              "Legoraft"
description:        "My blog, where I like to talk about gaming, programming and linux."
author_name:        "legoraft"
logo_url:           https://avatars.githubusercontent.com/u/50689727?v=4

url:                https://legoraft.com # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

defaults:
  - scope:
      path:         ""
    values:
      layout:       "null"
  - scope:
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      type:         "posts"
    values:
      layout:       "post"

highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain