baseURL = "http://example.org/"
languageCode = "en-us"
title = "Legoraft's blog"
theme = "lesser"
author = "Legoraft"

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
