base_url = "https://legoraft.com"

title = "Legoraft"
description = "My personal site, where I write about whatever and just have fun."
author = "Legoraft"

default_language = "en"

compile_sass = true
generate_feeds = true
feed_filenames = [ "rss.xml" ]

taxonomies = [
    { name = "tags", feed=false }
]

[markdown]
external_links_target_blank = true
