name: Build jekyll blog

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
  
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build blog with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.base_path }}
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v4
